### ISSUE TITLE
 AUTOCOP does not work

### ISSUE THREAD

**Issue by nqarubik** [val92130/Supreme-Auto-Checkout#12] opened 2017-08-31 01:00 UTC
It does not add a product

I do not know if it works in USA store, but it does not work in Japan store

**Comment by nqarubik** [comment] 2017-08-31 02:40
It only works in US strore
And Store Japan, it does not work

**Comment by val92130** [comment] 2017-08-31 05:29
Hey,
I just tested it and you're right, it doesn't work because on the Japan version of the shop it doesn't display the products' name so Autocop doesn't know what to look for.

I'll look at this and try to find a way to make it work.

**Comment by nqarubik** [comment] 2017-08-31 05:31
fix it
I think your bot will be complete
thanks you

**Comment by nqarubik** [comment] 2017-08-31 05:32
How long will it be completed?

**Comment by val92130** [comment] 2017-08-31 05:35
To be honest it might take some days to fix because I'll have to rewrite a big part of Autocop to find a way to get products' names if they aren't displayed on the shop

**Comment by nqarubik** [comment] 2017-08-31 05:36
OK, thank you very much <3

**Comment by nqarubik** [comment] 2017-09-03 07:52
Now, can you tell me the date of completion?
I'm looking forward to it

**Comment by val92130** [comment] 2017-09-04 08:21
Hey, it should be available in the next few days if everything goes well! :)

**Comment by nqarubik** [comment] 2017-09-04 14:21
Ok thanks you <3

**Comment by kushwiener** [comment] 2017-09-06 02:35
@val92130 Thank you this seems to be a legit bot much better than mine. 
If I wanted to put the Air Force 2's in Aqua coming out Thursday into the ATC product what would I put as the name and keyword? Like how close do I need to be to what it is actually called?

**Comment by val92130** [comment] 2017-09-06 08:16
Hey @kushwiener , thanks!
It should be easy for AutoCop to find the Air Force 2 since it's gonna be the only pair of shoes dropping this week.
The name doesn't matter but I recommend you to put those keywords: **Nike, Air, Force, 2, Two's, SB**. That should be it! It should work as long as the product name contains at least one of those keywords, which I'm 100% sure it will.
As for the color, just put Aqua and you should be fine :)

Would you mind keeping me updated if you manage to cop?

**Comment by nqarubik** [comment] 2017-09-09 04:08
Is it finished?

**Comment by val92130** [comment] 2017-09-11 09:01
No sorry not yet :( It's taking me more time than I thought, and I don't have time to fully focus on the project because of my job, I'll do my best to finish this asap

**Comment by nqarubik** [comment] 2017-09-11 14:37
ok thanks you :(

**Comment by nqarubik** [comment] 2017-09-11 15:29
Bot has problems !!!
It does not work on any Supreme web ....

**Comment by val92130** [comment] 2017-09-11 15:49
Okay I'll look into that when I'm home

**Comment by val92130** [comment] 2017-09-11 17:05
I don't have any issue with the bot, could you describe what the problem is?

**Comment by nqarubik** [comment] 2017-09-12 14:50
ok, it worked very well <3

**Comment by val92130** [comment] 2017-09-17 08:37
Hey, it should be working for Japan now! You'll have to check the "Use product monitor to find products" options.

You can try it out now by cloning the "develop" branch, it should be out soon in the chrome store.

**Comment by nqarubik** [comment] 2017-09-17 09:32
ok thanks you

**Comment by nqarubik** [comment] 2017-09-17 09:35
i will try

**Comment by nqarubik** [comment] 2017-09-17 09:50
AUTOCOP dont working :(

**Comment by val92130** [comment] 2017-09-17 09:57
When you go into the “Products” tab do you see a list of products?

**Comment by nqarubik** [comment] 2017-09-17 10:01
yes. 
So AUTOCOP can not work in JP

**Comment by nqarubik** [comment] 2017-09-17 10:03
![image](https://user-images.githubusercontent.com/31370784/30519834-17dae830-9bca-11e7-8ce2-66db81804d9f.png)

**Comment by val92130** [comment] 2017-09-17 10:08
I’m gonna try tonight with a japan proxy! It should be working

**Comment by nqarubik** [comment] 2017-09-17 10:16
ok
"product" is work but  "autocop" dont work in jp

**Comment by val92130** [comment] 2017-09-17 12:10
Have you tried with the Autocop timer or by clicking the “run now” button?

**Comment by nqarubik** [comment] 2017-09-18 15:10
WHY "Use product monitor to find products (Japan recommended)" WORKING
BUT
AUTOCOP DOESN'T WORKING ???

**Comment by val92130** [comment] 2017-09-18 15:14
What do you mean?

Could you tell me in detail what's not working so I can fix it please?

**Comment by nqarubik** [comment] 2017-09-18 15:22
Using "timer", it works
but
Click "run now" then it will not work

**Comment by val92130** [comment] 2017-09-18 15:25
Oh okay I see, you're right!

I'll try to quickly fix this.

**Comment by nqarubik** [comment] 2017-09-18 15:26
ok thanks you
Your bot is very good

**Comment by nqarubik** [comment] 2017-09-18 15:40
ok

**Comment by val92130** [comment] 2017-09-18 19:56
Could you try with the latest version in the "develop" branch? It should be fixed!

**Closed** 2017-09-18 20:30 UTC
Labels: bug
