### ISSUE TITLE
Unable to Auto Checkout Multiple Items

### ISSUE THREAD

**Issue by manbearcoon** [val92130/Supreme-Auto-Checkout#49] opened 2017-10-11 19:42 UTC
Been testing with the briefs and tee within accessories. I have both setup in AutoCop and both are enabled. With I hit RUN ALL, only the Tee shows up in the checkout screen. I noticed that only one tab (for the tee) opens up. I confirmed that pop-ups are allowed in Chrome.

If I hit run now manually, it'll cop each item and checkout, but not both for some reason. Trying on the US store.

Any idea? Running the latest version 2.7.1.

**Comment by manbearcoon** [comment] 2017-10-11 19:46
Something else I discovered about this issue.

As I said the Tee only shows. I noticed that this is the first item listed in AutoCop. If I remove Tee and then add it again (making the Boxer Briefs first in the list), I will hit RUN ALL and now only the Briefs are shown in autocheckout.

**Comment by val92130** [comment] 2017-10-11 19:58
Hey, thanks for reporting, I'll see if I can reproduce the issue!

**Comment by manbearcoon** [comment] 2017-10-11 20:04
No worries, thanks for the quick reply. One quick update. It seems to work when I have it using the AutoCop timer. It added both items (showed two tabs). So I think it's related to the RUN ALL function. Either way, great work so far and I really appreciate the effort that you put it. Hoping you're getting many donations.

**Comment by val92130** [comment] 2017-10-11 20:36
Thanks man! I only got one donation so far but I do it for the fun!

I just tried the 'run all' button with two products and two tabs opened as it should :/ I'm gonna release the new version today with a restock monitor so you'll never miss when a new product goes live! :)

**Comment by manbearcoon** [comment] 2017-10-11 20:39
I think it may be related to one of the timers. It happened again where it only carted one item. I manually navigated to the page of the item it missed and it automatically carted it. Seems like this is intermittent...happens sometimes.

**Comment by manbearcoon** [comment] 2017-10-11 20:52
Thanks again man. Anything else I can do to help let me know. I've been testing this quite extensively and can show you if needed. Definitely something off about the RUN ALL button as it only shows one tab, vs the scheduled task which will pop up the multiple tabs but no guarantee all will cart. For example, I did 3 items one time and only two were in the checkout page.

I confirmed all were in stock, including the sizes that I had configured. Also on the latest version of Chrome.

**Comment by tehisaac** [comment] 2017-10-12 02:17
I agree with @manbearcoon there seems to be something that prevents the cart from capturing all items carted. It'll run to checkout before grasping the actual totals from all items in cart and just shows the total of the first item. Seems like a refresh in the checkout page after all items carted will solve this so the item $$ will update @val92130 perhaps a good idea? You must be working on your update with Restocks rn! GL and always looking forward to more thank you

**Comment by val92130** [comment] 2017-10-12 05:30
Damn yeah you’re right, I’ll have to figure out a way to make this work :/

I’ve been really busy with the restock monitor update, and it turns out it’s more complicated than I thought! I won’t be releasing it today for the drop because I haven’t been able to test it enough to feel safe about releasing it to the public, I prefer to take my time than release a broken update :/

**Comment by CreatingMazes** [comment] 2017-10-12 05:32
So to clarify if we want to cop two products we have to use the Timer? Need to know because I’m leaving the bot do it’s thing while I go to school.

**Comment by val92130** [comment] 2017-10-12 07:39
Yes most likely, I also recommend you to login to your google account and solve some captchas on random websites to avoid a captcha during the drop

**Comment by CreatingMazes** [comment] 2017-10-12 18:38
Didn't get captcha, card got declined though it seems from the message I got to when I came home. But apparently this happened for loads of people this drop? Any way to test if I've been banned or idk

**Comment by val92130** [comment] 2017-10-12 21:53
Yeah I got card declined too :/ I copped a tee during a restock tho, and I don't know how to test if you've been banned or not sorry.

In the next update you'll be notified when a product restocks or drop on the store! :)

**Comment by val92130** [comment] 2017-10-15 22:01
Fixed in 2.8

**Closed by val92130** 2017-10-15 22:01 UTC
